# Generated by Django 3.0.7 on 2024-10-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('Limpiadores varios', 'Limpiadores varios'), ('Productos para piscinas', 'Productos para piscinas'), ('Higiene personal', 'Higiene personal'), ('Desodorantes de piso', 'Desodorantes de piso'), ('Ceras de pisos', 'Ceras de pisos'), ('Perfumes de telas', 'Perfumes de telas'), ('Lavado de ropas', 'Lavado de ropas'), ('Envases y afines', 'Envases y afines'), ('Difusores ambientales', 'Difusores ambientales'), ('Productos para autos', 'Productos para autos'), ('Escencias de perfumes y desodorantes', 'Escencias de perfumes y desodorantes')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_composite', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent_material', models.ForeignKey(blank=True, help_text='Define si este material es un submaterial de otro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submaterials', to='inventory.Stock')),
            ],
        ),
    ]
